[project]
name = "streamlit-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain-ollama>=1.0.1",
    "streamlit>=1.54.0",
]
